name: Build & Push Nextcloud to OCI Image Registry

on:
  push:
    branches:
      - master
    paths:
      - "src/Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - "src/Dockerfile"

jobs:
  workdirs:
    uses: ./.github/workflows/specify-workdir.yml
    with:
      base-dir: src

  image:
    uses: ./.github/workflows/build.yml
    needs: workdirs
    with:
      workdirs: ${{ needs.workdirs.outputs.workdirs-array }}
      images: |
        docker.io/hazmi35/nextcloud
        ghcr.io/hazmi35/nextcloud
    secrets:
      docker-hub-username: hazmi35
      docker-hub-access-token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      ghcr-username: ${{ github.repository_owner }}
      ghcr-access-token: ${{ secrets.GITHUB_TOKEN }}